name: Randomly send messages

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 7-17 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Send messages
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          python3 send_messages.py
